### ISSUE TITLE
Reusing provisioner.sh bash script

### ISSUE THREAD

**Issue by imesh** [wso2/vagrant-apim#12]
@ctienshi @VimukthiPerera As I see the difference between ```boxes/api-manager/provisioner/provisioner.sh``` and ```boxes/api-manager-analytics/provisioner/provisioner.sh``` is as follows:
````bash
< #!/bin/bash
---
> # This script acts as the machine provisioner during the Vagrant box build process for WSO2 Identity Analytics Server.
17c17,18
< WSO2_SERVER=wso2am
---
> # set variables
> WSO2_SERVER=wso2am-analytics
26d26
< CONFIGURATIONS=${DEFAULT_MOUNT}/identity-server/confs
31a32
>
45a47
>
87a90
>
95c98
<
---
> echo "Successfully removed APT cache"
````

Wouldn't it better to parameterize WSO2 server name and product component specific configurations and use a single script for this purpose?

**Comment by VimukthiPerera** [comment]
this has been fixed with https://github.com/wso2/vagrant-apim/pull/15

**Comment by DilanUA** [comment]
Closing as of above comment.
