### ISSUE TITLE
Integrating WUM for the vagrant box for APIM

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/vagrant-apim#6]
**Description:**
The Vagrant boxes which will be available for the general public, contains the GA package of each product. But a subscribed customer should be allowed to use the latest product version with the WUM updates. To allow this vagrant boxes should have WUM integrated

**Suggested Assignees:**
VimukthiPerera

**Comment by imesh** [comment]
Vimukthi, would you mind sharing your thoughts on the implementation design? How are you planning to implement this feature?

**Comment by VimukthiPerera** [comment]
Steps that I'm planning on following are:
1. Adding WUM to the Vagrant box. (This has already completed in https://github.com/wso2/vagrant-apim/pull/5
2. At the runtime, if the user has authentication make it possible to get a WUM update.

**Comment by imesh** [comment]
Thanks Vimukthi! I think it would be better to update this issue with the latest design which was discussed offline.
