### ISSUE TITLE
Wrong Git Repository URL in vagrant-apim/vagrantboxes/README.md

### ISSUE THREAD

**Issue by imesh** [wso2/vagrant-apim#7]
**Description:**
The git repository URL listed in vagrant-apim/vagrantboxes/README.md file seems to be wrong:
```
git clone https://github.com/wso2/vagrant-ei
```

**Comment by ctienshi** [comment]
This issue has been resolved in https://github.com/wso2/vagrant-apim/pull/10

**Comment by imesh** [comment]
Thanks @ctienshi!
