### ISSUE TITLE
Update root README.md Title

### ISSUE THREAD

**Issue by imesh** [wso2/vagrant-apim#8]
**Description:**
Currently the title of the root README.md has been set to "Vagrant-apim". I would like to propose to change this to "WSO2 API Manager Vagrant".

Examples:
https://github.com/dcos/dcos-vagrant
https://github.com/coreos/coreos-vagrant

**Comment by ctienshi** [comment]
This issue has been resolved in https://github.com/wso2/vagrant-apim/pull/10

**Comment by imesh** [comment]
Thanks @ctienshi!
