### ISSUE TITLE
Numbered bullet point formatting

### ISSUE THREAD

**Issue by imesh** [wso2/vagrant-apim#9]
**Description:**
As I see in vagrantfiles/README.md file numbered bullet points have been marked with four hashes:

```
## How to run the Vagrantfile

##### 1. Checkout this repository into your local machine using the following Git command.
git clone https://github.com/wso2/vagrant-apim

##### 2. Build Vagrant boxes for external MySQL database, WSO2 API Manager and API Manager Analytics using the Vagrant box automation resources.
...
```

This makes those lines to be displayed as bold. IMO it would be better to remove this formatting or use proper number of hashes if those lines need to be highlighted. I personally think it would be better to use standard numbered bullets without any formatting.

Examples:
https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md
https://github.com/dcos/dcos/blob/master/README.md

**Comment by imesh** [comment]
@DilanUA I think we have used this convention in other repositories as well. Please review!

**Comment by ctienshi** [comment]
This issue is resolved in https://github.com/wso2/vagrant-apim/pull/10

**Comment by imesh** [comment]
Thanks @ctienshi!
